### ISSUE TITLE
segmentation masks

### ISSUE THREAD

**Issue by wl03036530** [zc-alexfan/render_mano_ih#2]
Hi,
I am trying to make the segmentation masks by following the step in readme.
However, I have no idea if there is a problem with MANO_LEFT.pkl / MANO_RIGHT.pkl or which side is the problem, all the segmentation masks in the output file are black. (all value in the image is 0, but fitting error seems to be a normal value (The range is between 3 and 5 ))

I can not find the MANO_*.pkl in SMPL-X github, so I am trying to find that files in the author's previous work.
But the files I only found was created in 2018, and the file size is about 4MB. This make me confuse.

Could you please release your segmentation masks or provide  the MANO_*.pkl used in this project?
Thanks!

**Comment by zc-alexfan** [comment]
The segmentations are from the original InterHand2.6M dataset, so we cannot distribute it. Currently in the process of asking Facebook for permission.

**Comment by dqj5182** [comment]
As far as I know the InterHand2.6M dataset does not provide GT segmentation. Isn't it the case?
