### ISSUE TITLE
What is the order of the part-segmenation?

### ISSUE THREAD

**Issue by ZhengdiYu** [zc-alexfan/render_mano_ih#4]
![image](https://user-images.githubusercontent.com/63605407/165508902-2ec5111f-d9a0-44c8-898d-c2c09935ae57.png)
Do you have a map for your hand part segmentation like the pic above ? I didn't find it in either your paper or supplementary

**Comment by zc-alexfan** [comment]
I can send you the ID if you send me an email (zicong.fan@inf.ethz.ch).

**Comment by ZhengdiYu** [comment]
Thank you so much! I've sent you an email just now!
