### ISSUE TITLE
[BUG] Missing 10k + segmentations

### ISSUE THREAD

**Issue by ZhengdiYu** [zc-alexfan/render_mano_ih#5]
in main.py, there is:
frame_idx = op.basename(img_path)[5:-4]

However it should be convert to int then back to str: frame_idx = str(int(op.basename(img_path)[5:-4])), other wise. You will miss all the frames like 'image0XXX.jpg', which starts with '0', becuase this kind of key for MANO parameter dict, is '570' instead of '0570'...

Best,

**Comment by zc-alexfan** [comment]
Thanks Zhengdi. Could you do a pull request?
